# Generated by Django 3.2.3 on 2021-06-14 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0002_auto_20210611_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='CompanyName',
            new_name='nameofcompany',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='Typeofbeer',
            new_name='typeofbeer',
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('nameofcompany', 'typeofbeer')},
        ),
    ]
